[Desktop Entry]
Name=Win2-7(Pixmap)
Type=X-GNOME-Metatheme
Comment=Inspired on Win2-7 but without libia-ora engine

[X-GNOME-Metatheme]
GtkTheme=Win2-7-fixed
MetacityTheme=Win2-7-fixed
IconTheme=Win2-7
CursorTheme=aero-drop
CursorSize=18
#BackgroundImage=/usr/share/backgrounds/Win2-7.jpg
ButtonLayout=menu:minimize,maximize,close

#Fonts
ApplicationFont=Segoe UI 10
DocumentFont=Segoe UI 10
DesktopFont=Segoe UI 10
WindowTitleFont=Segoe UI 10
FixedWidthFont=Monospace 10
